### ISSUE TITLE
Timeout Overflow Warning

### ISSUE THREAD

**Issue by afief** [HOOQTV/tarik#11]
got `TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer. Timer duration was truncated to 2147483647.` when running on node 10.16.0. Need to check this line.

https://github.com/HOOQTV/tarik/blob/d23d6fa5abb4f02f6c8e1f0e9a4de042ec7c5843/fetch.js#L43

**Comment by Permagate** [comment]
Here is a possible fix: https://github.com/substack/hyperquest/pull/63/files

or just use `Number.MAX_SAFE_INTEGER`.

**Comment by afief** [comment]
Hi @Permagate , yes I've updated it like the one in https://github.com/substack/hyperquest/pull/63/files
btw, Number.MAX_SAFE_INTEGER is `9007199254740991` on my local machine. And still shows TimeoutOverflowWarning when doing `npm run test`
